apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: user-tracker
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
