version: "3.1"

services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: "users_logs"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"
